apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-adguard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-adguard-readonly-ingress
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
- apiGroups:
  - extensions
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-dns-adguard-role-binding
subjects:
- kind: ServiceAccount
  name: external-dns-adguard
  namespace: default
roleRef:
  kind: ClusterRole
  name: external-dns-adguard-readonly-ingress
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-adguard
  labels:
    app: external-dns-adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns-adguard
  template:
    metadata:
      labels:
        app: external-dns-adguard
    spec:
      serviceAccountName: external-dns-adguard
      containers:
      - name: external-dns-adguard
        image: pobek/external-dns-pihole:v0.1 # need to update
        env:
          - name: DOMAIN_NAME
            value: local.lan
          - name: ADGURED_DNS
            value: 192.168.3.100:8085
          - name: ADGURED_USER
            value: useraccount
          - name: ADGURED_PASS
            value: password
          - name: MODE
            value: PROD